name: Gradle build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest checkstyleIntegrationTest

      - name: Test
        run: ./gradlew test

      - name: Coverage report and further checks
        run: ./gradlew check

      - name: Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar
