name: Pipeline

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'adopt'

permissions:
  checks: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@master

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@main
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Check codestyle
        run: ./gradlew checkstyleMain checkstyleTest checkstyleIntegrationTest

  snyk:
    runs-on: ubuntu-latest
    needs: [checkstyle]
    steps:
      - name: Checkout the code
        uses: actions/checkout@main
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: ./gradlew snyk-test

  test-and-report:
    runs-on: ubuntu-latest
    needs: [checkstyle]
    steps:
      - name: Checkout the code
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      - name: Test
        run: ./gradlew test
      - name: Coverage report and further checks
        run: ./gradlew check
      - name: Sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar
